const KEY="venday-plus-v4",PKEY="venday-products-v1",EKEY="venday-expenses-v1";const $=id=>document.getElementById(id);const money=n=>Number(n||0).toLocaleString("pt-BR",{style:"currency",currency:"BRL"});const today=()=>new Date().toISOString().slice(0,10);let sales=JSON.parse(localStorage.getItem(KEY)||"[]"),products=JSON.parse(localStorage.getItem(PKEY)||"[]"),expenses=JSON.parse(localStorage.getItem(EKEY)||"[]");
if($("date"))$("date").value=today();$("due").value=today();$("from").value=firstDay();$("to").value=today();$("cashFrom").value=firstDay();$("cashTo").value=today();$("inst").disabled=true;
document.querySelectorAll(".tab").forEach(b=>b.onclick=()=>show(b.dataset.view));$("payment").onchange=()=>{let p=$("payment").value==="parcelado";$("inst").disabled=!p;if(!p)$("inst").value=1};
function show(v){document.querySelectorAll(".view").forEach(x=>x.classList.remove("active"));$(v).classList.add("active");document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.dataset.view===v));if(v==="clients")renderClients();if(v==="products")renderProducts();if(v==="cash")renderCash();if(v==="reports")runReport()}
$("saleForm").onsubmit=e=>{e.preventDefault();let value=+$("value").value,cost=+$("cost").value||0,inst=Math.max(1,Math.min(60,+$("inst").value||1));if(!value)return;let arr=[];for(let i=0;i<inst;i++)arr.push({n:i+1,value:value/inst,due:addMonths($("due").value,i),paid:false});sales.unshift({id:crypto.randomUUID(),client:$("client").value.trim(),phone:$("phone").value.trim(),product:$("product").value.trim(),qty:+$("qty").value||1,value,cost,date:$("date").value,installments:arr});save();e.target.reset();if($("date"))$("date").value=today();$("due").value=today();$("inst").value=1;$("inst").disabled=true;render();show("home")};
function save(){localStorage.setItem(KEY,JSON.stringify(sales))}function addMonths(date,n){let d=new Date(date+"T00:00:00");d.setMonth(d.getMonth()+n);return d.toISOString().slice(0,10)}function firstDay(){let d=new Date();return new Date(d.getFullYear(),d.getMonth(),1).toISOString().slice(0,10)}function fmt(d){return d?d.split("-").reverse().join("/"):"—"}function late(i){return !i.paid&&i.due<today()}
function totals(){let sold=sales.reduce((a,s)=>a+s.value,0),rec=sales.reduce((a,s)=>a+s.installments.filter(i=>i.paid).reduce((x,i)=>x+i.value,0),0),profit=sales.reduce((a,s)=>a+(s.value-s.cost),0);return{sold,rec,open:sold-rec,profit}}
function render(){let t=totals();$("sold").textContent=money(t.sold);$("received").textContent=money(t.rec);$("open").textContent=money(t.open);$("profit").textContent=money(t.profit);$("homeList").innerHTML=sales.slice(0,7).map(card).join("")||empty()}
function card(s){let paid=s.installments.filter(i=>i.paid).length;return `<article class="card"><div class="topline"><div><div class="name">${esc(s.client)}</div><div class="muted">${esc(s.product)} · ${s.qty} un.</div></div><div class="money">${money(s.value)}</div></div><span class="pill">${paid}/${s.installments.length} pagas</span><span class="pill">Próx.: ${next(s)}</span><div class="actions"><button onclick="toggle('${s.id}')">Parcelas</button>${s.phone?`<button onclick="whats('${s.id}')">Cobrar WhatsApp</button>`:""}</div><div id="d-${s.id}" class="installments" hidden>${s.installments.map((i,k)=>`<div class="installment"><div><b>${k+1}ª parcela</b><div class="muted">${money(i.value)} · ${fmt(i.due)}</div></div><button class="${i.paid?'paid':''}" onclick="pay('${s.id}',${k})">${i.paid?'Pago':'Marcar paga'}</button></div>`).join("")}</div></article>`}
function next(s){let i=s.installments.find(x=>!x.paid);return i?fmt(i.due):"Quitado"}function toggle(id){let e=$("d-"+id);e.hidden=!e.hidden}function pay(id,k){let s=sales.find(x=>x.id===id);s.installments[k].paid=!s.installments[k].paid;save();render();renderClients();renderCash();runReport()}function whats(id){let s=sales.find(x=>x.id===id),i=s.installments.find(x=>!x.paid);if(!i)return;let phone=s.phone.replace(/\D/g,"");let msg=`Olá, ${s.client}! 😊 Passando para lembrar da sua parcela de ${money(i.value)}, com vencimento em ${fmt(i.due)}. Qualquer dúvida, estou à disposição!`;window.open("https://wa.me/55"+phone+"?text="+encodeURIComponent(msg),"_blank")}
function renderClients(){let q=$("clientSearch").value.trim().toLowerCase(),map={};sales.forEach(s=>{let k=s.client;if(!map[k])map[k]={name:k,phone:s.phone,total:0,count:0,open:0};map[k].total+=s.value;map[k].count++;map[k].open+=s.installments.filter(i=>!i.paid).reduce((a,i)=>a+i.value,0)});let arr=Object.values(map).filter(c=>c.name.toLowerCase().includes(q)).sort((a,b)=>b.total-a.total);$("clientsList").innerHTML=arr.length?arr.map(c=>`<article class="card"><div class="topline"><div><div class="name">${esc(c.name)}</div><div class="muted">${c.phone||"Sem WhatsApp cadastrado"}</div></div><b>${money(c.total)}</b></div><span class="pill">${c.count} compra(s)</span><span class="pill">${money(c.open)} a receber</span></article>`).join(""):empty()}
$("clientSearch").oninput=renderClients;
$("productForm").onsubmit=e=>{e.preventDefault();products.unshift({id:crypto.randomUUID(),name:$("pname").value.trim(),price:+$("pprice").value,cost:+$("pcost").value||0,stock:+$("pstock").value||0});localStorage.setItem(PKEY,JSON.stringify(products));e.target.reset();renderProducts()};
function renderProducts(){$("productsList").innerHTML=products.length?products.map((p,i)=>`<article class="card"><div class="topline"><div><div class="name">${esc(p.name)}</div><div class="muted">Custo ${money(p.cost)} · Estoque ${p.stock}</div></div><b>${money(p.price)}</b></div><span class="pill">Margem: ${money(p.price-p.cost)}</span><div class="actions"><button onclick="deleteProduct(${i})">Excluir</button></div></article>`).join(""):empty()}function deleteProduct(i){products.splice(i,1);localStorage.setItem(PKEY,JSON.stringify(products));renderProducts()}
function renderCash(){let f=$("cashFrom").value,t=$("cashTo").value,entries=[];sales.forEach(s=>s.installments.forEach(i=>{if(i.paid&&i.due>=f&&i.due<=t)entries.push({date:i.due,desc:s.client+" — "+s.product,value:i.value})}));let ent=entries.reduce((a,x)=>a+x.value,0),out=expenses.filter(e=>e.date>=f&&e.date<=t).reduce((a,e)=>a+e.value,0);$("cashResult").innerHTML=`<div class="metric"><small>Entradas</small><b>${money(ent)}</b></div><div class="metric"><small>Saídas</small><b>${money(out)}</b></div><div class="metric"><small>Saldo</small><b>${money(ent-out)}</b></div>`;$("cashEntries").innerHTML=entries.sort((a,b)=>b.date.localeCompare(a.date)).map(e=>`<div class="card"><b>${money(e.value)}</b> · ${fmt(e.date)}<div class="muted">${esc(e.desc)}</div></div>`).join("")||'<p class="muted">Nenhuma entrada.</p>';$("expenses").innerHTML=expenses.filter(e=>e.date>=f&&e.date<=t).map((e,i)=>`<div class="card"><b>Saída ${money(e.value)}</b> · ${fmt(e.date)}<div class="muted">${esc(e.desc)}</div></div>`).join("")}
$("cashFrom").onchange=renderCash;$("cashTo").onchange=renderCash;
function addExpense(){let desc=prompt("Descrição da saída:");if(!desc)return;let val=Number(prompt("Valor da saída:"));if(!val||val<0)return;expenses.unshift({date:today(),desc,value:val});localStorage.setItem(EKEY,JSON.stringify(expenses));renderCash()}
function runReport(){let f=$("from").value,t=$("to").value;if(!f||!t||f>t){$("reportResult").innerHTML='<div class="card muted">Informe um período válido.</div>';return}let a=sales.filter(s=>s.date>=f&&s.date<=t),total=a.reduce((x,s)=>x+s.value,0),pieces=a.reduce((x,s)=>x+s.qty,0),received=a.reduce((x,s)=>x+s.installments.filter(i=>i.paid).reduce((y,i)=>y+i.value,0),0),profit=a.reduce((x,s)=>x+s.value-s.cost,0),clients={};a.forEach(s=>clients[s.client]=(clients[s.client]||0)+s.value);let top=Object.entries(clients).sort((x,y)=>y[1]-x[1]).slice(0,5),max=top[0]?.[1]||1;$("reportResult").innerHTML=`<div class="card"><h2>Relatório ${fmt(f)} a ${fmt(t)}</h2><div class="reportGrid"><div class="metric"><small>Vendas</small><b>${a.length}</b></div><div class="metric"><small>Peças</small><b>${pieces}</b></div><div class="metric"><small>Vendido</small><b>${money(total)}</b></div><div class="metric"><small>Recebido</small><b>${money(received)}</b></div><div class="metric"><small>A receber</small><b>${money(total-received)}</b></div><div class="metric"><small>Lucro estimado</small><b>${money(profit)}</b></div></div><h3>Top clientes</h3>${top.map(x=>`<div style="margin:10px 0"><div class="topline"><span>${esc(x[0])}</span><b>${money(x[1])}</b></div><div class="bar"><i style="width:${Math.max(4,x[1]/max*100)}%"></i></div></div>`).join("")||'<p class="muted">Sem vendas no período.</p>'}<h3>Detalhamento</h3><table class="table"><tr><th>Data</th><th>Cliente</th><th>Produto</th><th>Total</th></tr>${a.map(s=>`<tr><td>${fmt(s.date)}</td><td>${esc(s.client)}</td><td>${esc(s.product)}</td><td>${money(s.value)}</td></tr>`).join("")}</table></div>`}
function empty(){return '<div class="card muted">Nenhum registro encontrado.</div>'}function esc(x){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}
let deferredPrompt=null;addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferredPrompt=e;$("install").classList.remove("hidden")});$("install").onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$("install").classList.add("hidden")};if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(console.error);render();